# version: "1.0"

services:

  flexget:
#    image: flexget-custom
#    image: wiserain/flexget:latest
    image: lscr.io/linuxserver/flexget:latest
    container_name: flexget
    restart: unless-stopped

    volumes:
      - ${FLEX_config}:/config
      - ${FLEX_config}/custom-cont-init.d:/custom-cont-init.d:ro
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage

    ports:
      - "127.0.0.1:5050:5050"  # Solo localhost (detrás de Traefik)

    environment:
      - TZ=${FLEX_TZ}
      - PUID=${FLEX_PUID}
      - PGID=${FLEX_PGID}
      - TORRENT_PLUGIN=${FLEX_TORRENT_PLUGIN}
      - FG_WEBUI_PASSWORD=${FLEX_FG_WEBUI_PASSWD}

      - FG_LOG_LEVEL=info
      - FG_LOG_FILE=/config/.flexget/flexget.log
      - FG_CONFIG_FILE=/config/.flexget/config.yml  # Ruta explícita


    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flexget.entrypoints=https"
      - "traefik.http.routers.flexget.rule=Host(`$FLEX_URL`)"
      - "traefik.http.routers.flexget.tls=true"
      - "traefik.http.routers.flexget.tls.certresolver=myresolver"
      - "traefik.http.routers.flexget.service=flexget"
      - "traefik.http.services.flexget.loadbalancer.server.port=5050"

    networks:
      kronos-net:
        ipv4_address: 172.20.0.12  # IP fija para Flexget
    dns:
      - 172.20.0.2  # Usa Pi-hole como DNS

networks:
  kronos-net:
    external: true

