services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=kronos.cloudns.ph
      - PROXIED=true
      - TTL=1
      - UPDATE_CRON=@every 5m
    network_mode: "host"