#version: '1'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:2.1.0
    container_name: cloudflare
    restart: always
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${CLOUDFLARE_ZONE}
      - PROXIED=false

    env_file:
      - .env

    network_mode: "host"

